{{- if .Values.webhook.caBundle.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kube-sentry.fullname" . }}
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
  labels:
    {{- include "kube-sentry.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kube-sentry.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
  labels:
    {{- include "kube-sentry.labels" . | nindent 4 }}
spec:
  secretName: {{ include "kube-sentry.fullname" . }}-cert
  dnsNames:
    - {{ include "kube-sentry.fullname" . }}.{{.Release.Namespace}}.svc
  issuerRef:
    name: {{ include "kube-sentry.fullname" . }}
{{- end }}