apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signer
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-sentry-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  secretName: {{.Values.webhook.caBundle.certmanager.secretName}}
  dnsNames:
{{- toYaml .Values.webhook.caBundle.certmanager.dnsNames | nindent 4 }}
  issuerRef:
    name: self-signer