apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signer
  namespace: kube-sentry
  annotations:
    "helm.sh/hook": pre-install
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-sentry-cert
  namespace: kube-sentry
  annotations:
    "helm.sh/hook": pre-install
spec:
  secretName: kube-sentry-cert-secret
  dnsNames:
    - kube-sentry
    - kube-sentry.kube-sentry
    - kube-sentry.kube-sentry.svc
  issuerRef:
    name: self-signer