apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-sentry.fullname" . }}
  labels:
    {{- include "kube-sentry.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-sentry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-sentry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-sentry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --tls-cert-file={{ .Values.image.args.tlsCertFile }}
          - --tls-key-file={{ .Values.image.args.tlsKeyFile }}
          - --insecure={{ .Values.image.args.insecure }}
          - --listen-addr={{ .Values.image.args.listenAddr }}
          - --metrics-addr={{ .Values.image.args.metricsAddr }}
          - --trivy-addr={{ .Values.image.args.trivyAddr }}
          - --trivy-scheme={{ .Values.image.args.trivyScheme }}
          - --metrics-labels={{ .Values.image.args.metricsLabels }}
          - --sentry-mode={{ .Values.image.args.sentryMode }}
          - --forbidden-cves={{ .Values.image.args.forbiddenCves}}
          - --num-critical-cves={{ .Values.image.args.numCriticalCves }}
          - --num-allowed-cves={{ .Values.image.args.numAllowedCves }}
          ports:
            {{- toYaml .Values.image.ports | nindent 12 }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: kube-sentry-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
