kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: {{ include "kube-sentry.fullname" . }}
  labels:
    {{- include "kube-sentry.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.webhook.caBundle.certmanager.enabled }}
    cert-manager.io/inject-ca-from: {{.Release.Namespace}}/{{ include "kube-sentry.fullname" . }}-cert # namespace/secretName
    {{- end }}
webhooks:
  - name: {{ include "kube-sentry.fullname" . }}.{{.Release.Namespace}}.svc
    failurePolicy: Ignore # still forward api requests when unexpected errors are returned (expected failures still block pod creation)
    clientConfig:
      {{- if not .Values.webhook.caBundle.certmanager.enabled }}
      caBundle: {{ .Values.webhook.caBundle.value }}
      {{- end }}
      service:
        namespace: {{.Release.Namespace}}
        name: kube-sentry
        path: /validate
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE"]
        scope: "*"
    sideEffects: None
    admissionReviewVersions: ["v1"]