kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kube-sentry
  annotations:
    helm.sh/hook: post-install
{{- toYaml .Values.webhook.caBundle.certmanager.annotations | nindent 4 }}
webhooks:
  - name: kube-sentry.kube-sentry.svc
    clientConfig:
      {{- if not .Values.webhook.caBundle.certmanager.enabled }}
      caBundle: {{ .Values.webhook.caBundle.value }}
      {{- end }}
      service:
        namespace: {{.Release.Namespace}}
        name: kube-sentry
        path: /validate
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE", "UPDATE"]
        scope: Namespaced
    sideEffects: None
    admissionReviewVersions: ["v1"]