apiVersion: v2
name: kube-sentry
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: trivy
    version: "0.4.17"
    repository: https://aquasecurity.github.io/helm-charts/
    condition: trivy.enabled
    tags:
      - trivy