apiVersion: v2
name: kube-sentry
description: Defend against high-risk workloads and gain visibility into vulnerable containers running on Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
sources:
  - https://github.com/tks98/kube-sentry
maintainers:
  - name: Travis Smith
    email: travis.kenneth.smith@gmail.com
    url: https://github.com/tks98

dependencies:
  - name: trivy
    version: "0.4.17"
    repository: https://aquasecurity.github.io/helm-charts/
    condition: trivy.enabled
    tags:
      - trivy